# See https://pre-commit.com for more information
# Minimal pre-commit to be compatible with current GitHub Actions style.yml

default_language_version:
  python: python3.7

default_stages: [commit, push]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--check"]
        exclude: ^[src/python/zquantum/core/openfermion/|tests/zquantum/core/openfermion_tests/]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--check"]
        language_version: python3.8
        exclude: ^[src/python/zquantum/core/openfermion/|tests/zquantum/core/openfermion_tests/]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        exclude: ^[src/python/zquantum/core/openfermion/|tests/zquantum/core/openfermion_tests/]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        exclude: ^[src/python/zquantum/core/openfermion/|tests/zquantum/core/openfermion_tests/]
